kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-website-canary
  labels:
    app: nginx
    env: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: backend
      labels:
        app: nginx
        role: backend
        env: canary
    spec:
      containers:
      - name: backend
        image: gcr.io/spinnaker-334105/nginx-website
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        env:
        - name: COMPONENT
          value: backend
        - name: VERSION
          value: canary
        ports:
        - name: backend
          containerPort: 80