kind: Deployment
apiVersion: apps/v1
metadata:
  name: 'nginx-website-production-${parameters.release}'
  labels:
    app: nginx
    release: '${parameters.release}'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: backend
      labels:
        app: nginx
        role: backend
        env: production
        release: '${parameters.release}'
    spec:
      containers:
      - name: backend
        image: gcr.io/spinnaker-334105/nginx-website
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        env:
        - name: COMPONENT
          value: backend
        - name: VERSION
          value: production
        ports:
        - name: backend
          containerPort: 80
