
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-website-production
  name: nginx-website-production
spec:
  ports:
  - name: 8080-80
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: sample
    role: backend
  sessionAffinity: None
  type: ClusterIP
