apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-website-canary
  name: nginx-website-canary
spec:
  ports:
  - name: 8080-80
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
    role: backend
    env: canary
  sessionAffinity: None
  type: LoadBalancer
